// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loading': string;
  'loading__bottom': string;
  'loading__left': string;
  'loading__right': string;
  'loading__top': string;
  'slideBottom': string;
  'slideLeft': string;
  'slideRight': string;
  'slideTop': string;
}
export const cssExports: CssExports;
export default cssExports;
