// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'identifier': string;
  'nav': string;
  'nav__link': string;
  'nav__menu': string;
  'nav__menuInput': string;
  'nav__selected': string;
  'nav__tab': string;
  'nav__tabs': string;
  'nav__title': string;
}
export const cssExports: CssExports;
export default cssExports;
