// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'quiz': string;
  'quiz__button': string;
  'quiz__buttonStart': string;
  'quiz__container': string;
  'quiz__header': string;
  'quiz__headerResult': string;
  'quiz__input': string;
  'quiz__question': string;
}
export const cssExports: CssExports;
export default cssExports;
