// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'beat': string;
  'home': string;
  'home__background': string;
  'home__video': string;
}
export const cssExports: CssExports;
export default cssExports;
