// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fadeInOut': string;
  'modal': string;
  'modal__close': string;
  'modal__fadeIn': string;
}
export const cssExports: CssExports;
export default cssExports;
