// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'table': string;
  'table__container': string;
}
export const cssExports: CssExports;
export default cssExports;
