// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'confetti': string;
  'confetti__container': string;
  'fall': string;
}
export const cssExports: CssExports;
export default cssExports;
